KEYS = {
    #Key for debug
    'ConsumerkeySOTAwatch2':'',
    'ConsumersecretSOTAwatch2':'',
    'AccesstokenSOTAwatch2':'',
    'AccesstokensecretSOTAwatch2':'',
    #Key for SOTAwatchspot JA
    'ConsumerkeySOTAwatch':'',
    'ConsumersecretSOTAwatch':'',
    'AccesstokenSOTAwatch':'',
    'AccesstokensecretSOTAwatch':'',
    'Areas':r'^JA.*',
    'Alerts':r'JA\d*/\w\w\-',
    'JASummits':r'JA\d*/\w\w\-',
    'Watchfor':r'JA\d*/\w\w\-',
    'Alertafter':('Asia/Tokyo',6),
    'LOCALTIME':True,
    'MapURL':'https://maps.google.co.jp/maps?q={place}&ll={locate}&t=h&z=12',
    'VOACAP':'/home/ubuntu/pi/twitter/propdb.db',
    'VOAIMG':'/tmp/voaimg.png',

    'SOTA_URL':'http://www.sotawatch.org/alerts.php',
    'SOTA_JSON_URL':'https://sota-api2.azurewebsites.net/api/alerts?',
    'SUMMIT_DB':'/home/ubuntu/pi/SOTAspotJA/summit_data/aprs-summit.db',
    'DXSUMMIT_DB':'/home/ubuntu/pi/SOTAspotJA/summit_data/aprs-dx-summit.db',
    'BEACON_DB':'/home/ubuntu/pi/SOTAspotJA/beacon.db',
    'ALERT_DB':'/home/ubuntu/pi/SOTAspotJA/alert.db',
    'LAST3':"/home/ubuntu/pi/twitter/lastspot.txt",
    'LAST3DX':"/home/ubuntu/pi/twitter/lastspotdx.txt",
    'APRS_USER':'',
    'APRS_PASSWD':'',
    'APRS_HOST':'japan.aprs2.net',
    'APRS_PORT':14580,
    'TWEET_AT':"08:00",
    'ALERT_FROM':-4,
    'ALERT_TO':16,
    'UPDATE_EVERY':20,
    'WINDOW_FROM':-4,
    'WINDOW_TO':5,
    'MAGNIFY':10.0,
    'TEST_USER':[],
    'EXCLUDE_USER':[]
}
