KEYS = {
    'Consumerkey':'',
    'Consumersecret':'',
    'Accesstoken':'',
    'Accesstokensecret':'',

    'Consumerkey2':'',
    'Consumersecret2':'',
    'Accesstoken2':'',
    'Accesstokensecret2':'',

    'ConsumerkeySOTAwatch':'',
    'ConsumersecretSOTAwatch':'',
    'AccesstokenSOTAwatch':'',
    'AccesstokensecretSOTAwatch':'',

    'JAFFConsumerkey':'',
    'JAFFConsumersecret':'',
    'JAFFAccesstoken':'',
    'JAFFAccesstokensecret':'',

    'Areas':r'^JA.*',
    'Alerts':r'JA\d*/\w\w\-',
    'JASummits':r'JA\d*/\w\w\-',
    'Alertafter':('Asia/Tokyo',6),
    'LOCALTIME':True,
    'MapURL':'https://maps.google.co.jp/maps?q={place}&ll={locate}&t=h&z=12',
    'VOACAP':'/home/ubuntu/pi/twitter/propdb.db',
    'VOAIMG':'/tmp/voaimg.png',

    'SOTA_URL':'http://www.sotawatch.org/alerts.php',
    'SUMMIT_DB':'/home/ubuntu/pi/SOTAspotJA/summit_data/aprs-summit.db',
    'BEACON_DB':'/home/ubuntu/pi/SOTAspotJA/beacon.db',
    'ALERT_DB':'/home/ubuntu/pi/SOTAspotJA/alert.db',
    'LAST3':"/home/ubuntu/pi/twitter/lastspot.txt",
    'LAST3DX':"/home/ubuntu/pi/twitter/lastspotdx.txt",
    'APRS_USER':'',
    'APRS_PASSWD':'',
    'APRS_HOST':'japan.aprs2.net',
    'APRS_PORT':14580,
    'TWEET_AT':"08:00",
    'ALERT_FROM':-4,
    'ALERT_TO':16,
    'UPDATE_EVERY':20,
    'WINDOW_FROM':-4,
    'WINDOW_TO':5,
    'MAGNIFY':10.0,
    'TEST_USER':[],
    'EXCLUDE_USER':[]
}
